VERSION="1.0.0"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="Sanca"
ORG_URL="https://www.sanca.space"
ORG_DESCRIPTION="Arisan (ROSCA) on-chain"
ORG_SUPPORT_EMAIL="tgraji.k@gmail.com"
